volumes:
  posts-data:
  minio-data:

services:
  posts-db:
    image: pgvector/pgvector:pg17-trixie
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: posts
    ports:
      - "6432:5432"
    volumes:
      - posts-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
  
  posts-api:
    image: ${DOCKER_REGISTRY-}postsapi
    build:
      context: .
      dockerfile: src/Posts.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
      JwtOptions__Issuer: "PostsApi"
      JwtOptions__Audience: "PostsFrontend"
      JwtOptions__Key: "PUT_32+_SYMBOLS_RANDOM_KEY_HERE________________"
      JwtOptions__ExpiresMinutes: 20
      EncryptionOptions__EncryptionKey: "PUT_32+_SYMBOLS_RANDOM_KEY_HERE________________"
      S3Options__ServiceUrl: "http://minio:9000"
      S3Options__AccessKey: "minioadmin"
      S3Options__SecretKey: "minioadmin"
      S3Options__BucketName: "my-bucket"
      S3Options__ForcePathStyle: true
      S3Options__PublicDomain: "http://localhost:9000"
      ConnectionStrings__PostsDatabase: "Host=posts-db;Port=5432;Database=posts;Username=postgres;Password=postgres"
      RunMigrations: true
      S3Configure: true
    ports:
      - 5062:8080
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - posts-db
      - minio